### PR TITLE
Update Persistence

### PR DESCRIPTION
**Pull request by YuanL12**

### CODE REVIEW

**Comment by YuanL12** [comment]
Hi Brad,

This is my implementation of updating persistence. I also included two test files: 
tests/update_general.cpp and tests/update_rips.cpp.
The difference between these two is that the first one is **not** required to assume that the cells in the filtration have been sorted by their filtration values at the time of the construction of the filtration, but the second one is required to (like rips filtration).

Best,
Yuan

**Comment by YuanL12** [comment]
This pull request include the general method of updating persistence, and the inverse map of Rips Filtration. 
You can see the demo implementation in 
tests/inverse_map.cpp, tests/update_rips.cpp.

**Comment by bnels** [comment]
One more thing: please remove `.DS_store` from version control (and add it to the `.gitignore` file)

**Comment by bnels** [comment]
I've gone ahead and merged.  Thanks!

**Pull request merged**
